/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with email and password
         * @description Authenticates the user via email + password. Handled by the `json_login` firewall.
         *
         *     **Without 2FA**: returns `access_token`, `refresh_token`, and a `user` summary.
         *     **With 2FA enabled**: returns `requires_2fa: true`, a short-lived `pre_auth_token`, and the `two_factor_method`.
         *     The client must then call `POST /auth/two-factor` with the pre-auth token and TOTP/email code.
         *
         *     Rate limited: 5 attempts/minute per IP.
         */
        post: operations["post_api_auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get RSA public key
         * @description Returns the RSA public key used for JWT signature verification. Used by the legacy Symfony 3.4 backend.
         */
        get: operations["get_api_auth_public_key"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new account
         * @description Creates a new user account. If a matching legacy user is found by username, the account is automatically
         *     linked and profile data (person, contact, address, company) is hydrated from the legacy system.
         *
         *     On success, returns tokens immediately (user is auto-logged-in).
         *     Accepts both camelCase (`firstName`) and snake_case (`first_name`) for backward compatibility.
         *
         *     Rate limited: 10 registrations/hour per IP.
         */
        post: operations["post_api_auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/two-factor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete login with 2FA code
         * @description Second step of the login flow when 2FA is enabled. The client submits the pre-auth token
         *     received from POST /auth/login along with the 6-digit TOTP or email OTP code.
         *
         *     On success, returns full `access_token` and `refresh_token`.
         *
         *     Rate limited: 5 attempts/5 minutes per IP.
         */
        post: operations["post_api_auth_two_factor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Exchanges a valid refresh token for a new access_token + refresh_token pair.
         *     The old refresh token is consumed (single-use). If the token is invalid, expired,
         *     or already revoked, returns 401.
         *
         *     Rate limited: 10 requests/minute per IP.
         */
        post: operations["post_api_auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout and revoke session
         * @description Revokes the current session's refresh token and session record. Requires a valid JWT.
         */
        post: operations["post_api_auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request password reset OTP
         * @description Sends a 6-digit OTP to the user's email address. Always returns success even if the email
         *     is not registered (to prevent email enumeration).
         *
         *     Rate limited: 3 requests/hour per IP.
         */
        post: operations["post_api_auth_forgot_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-reset-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify password reset OTP
         * @description Validates the 6-digit OTP sent via email. On success, returns a one-time `reset_token`
         *     that must be used with POST /auth/reset-password.
         *
         *     Rate limited: 5 attempts/15 minutes per IP.
         */
        post: operations["post_api_auth_verify_reset_code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset password with reset token
         * @description Sets a new password using the reset token obtained from POST /auth/verify-reset-code.
         *     Revokes all existing refresh tokens for the user (forces re-login on all devices).
         */
        post: operations["post_api_auth_reset_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/2fa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable two-factor authentication
         * @description Initiates 2FA setup. For `method=totp`, returns a TOTP secret and provisioning URI (for QR code).
         *     The client must then call POST /auth/2fa/confirm with a valid TOTP code to activate it.
         *     For `method=email`, 2FA is enabled immediately using email-based OTP codes.
         */
        post: operations["post_api_auth_two_factor_enable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/2fa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm TOTP 2FA setup
         * @description Verifies the first TOTP code to confirm the secret is set up correctly. After this call, 2FA is fully active.
         */
        post: operations["post_api_auth_two_factor_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/2fa/resend-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend 2FA email code
         * @description Resends the 2FA email OTP code during the login flow. Requires a valid pre_auth_token
         *     and only works when the user's 2FA method is "email".
         *
         *     Rate limited: 3 requests/10 minutes per IP.
         */
        post: operations["post_api_auth_two_factor_resend_code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/2fa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable two-factor authentication
         * @description Disables 2FA for the authenticated user. Requires current password for confirmation.
         */
        post: operations["post_api_auth_two_factor_disable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dashboard statistics
         * @description Returns aggregated counts and highlights for the authenticated user:
         *     - Policy totals, active count, breakdown by type, and policies expiring within 30 days
         *     - Quote totals and pending count
         *     - Notification totals and unread count
         *     - Upcoming reminders (next 7 days, not done) and total count
         */
        get: operations["get_api_dashboard_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all notifications
         * @description Returns all notifications for the authenticated user, ordered by creation date (newest first).
         */
        get: operations["get_api_notifications_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark notification as read
         * @description Marks a single notification as read.
         */
        patch: operations["patch_api_notifications_mark_read"];
        trace?: never;
    };
    "/api/user/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark all notifications as read
         * @description Marks all notifications for the authenticated user as read in a single operation.
         */
        patch: operations["patch_api_notifications_mark_all_read"];
        trace?: never;
    };
    "/api/user/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete notification
         * @description Permanently deletes a single notification.
         */
        delete: operations["delete_api_notifications_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List policies
         * @description Returns a paginated list of the authenticated user's insurance policies. Supports filtering by status and type.
         */
        get: operations["get_api_policies_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get policy details
         * @description Returns full details for a single policy. Returns 404 if the policy doesn't exist or belongs to another user.
         */
        get: operations["get_api_policies_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/policies/download/{transactionId}/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get policy document download URL
         * @description Returns an encrypted download URL for a policy document.
         *     The transactionId and fileId are available from the policy's transactionId and fileIds fields.
         *     The fileId is one of the values from the policy's fileIds map (e.g. fileIds.policy_pdf).
         *     The returned URL can be opened directly in the browser to download the PDF.
         */
        get: operations["get_api_policies_download_document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/policies/sync-states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List policy sync states
         * @description Returns sync state records for the user's policies.
         */
        get: operations["get_api_policies_sync_states"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List quotes
         * @description Returns a paginated list of the authenticated user's insurance quotes. Supports filtering by active state and type.
         */
        get: operations["get_api_quotes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/quotes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get quote details
         * @description Returns full details for a single quote. Returns 404 if the quote doesn't exist or belongs to another user.
         */
        get: operations["get_api_quotes_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/quotes/offer-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get offer URL for a quote
         * @description Requests the offer/results page URL from the legacy system. The quoteInputParamsId is available from the sync states endpoint.
         */
        post: operations["post_api_quotes_offer_url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/quotes/sync-states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List quote sync states
         * @description Returns sync state records for the user's quotes. Each record contains quoteInputParamsId needed for the offer-url endpoint.
         */
        get: operations["get_api_quotes_sync_states"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reminders
         * @description Returns all reminders for the authenticated user.
         */
        get: operations["get_api_reminders_list"];
        put?: never;
        /**
         * Create reminder
         * @description Creates a new reminder with a title, date, and optional note.
         */
        post: operations["post_api_reminders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/reminders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update reminder
         * @description Updates one or more fields of an existing reminder. All fields are optional.
         */
        put: operations["put_api_reminders_update"];
        post?: never;
        /**
         * Delete reminder
         * @description Permanently deletes a reminder.
         */
        delete: operations["delete_api_reminders_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active sessions
         * @description Returns all active sessions for the authenticated user. Each session includes a `current` flag indicating which session belongs to the current request.
         */
        get: operations["get_api_sessions_list"];
        put?: never;
        post?: never;
        /**
         * Revoke all other sessions
         * @description Revokes all sessions except the current one (identified by the JWT session ID). Effectively logs out all other devices.
         */
        delete: operations["delete_api_sessions_delete_all"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a specific session
         * @description Revokes a specific session and its associated refresh token. Cannot revoke the current session (use POST /auth/logout instead).
         */
        delete: operations["delete_api_sessions_delete_one"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/sync/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Refresh sync
         * @description Polls the legacy system for data changes since the last sync.
         *     Intended to be called by the frontend every 10 minutes while the user is active.
         *     Returns a summary of what changed (new/updated policies and quotes).
         */
        get: operations["get_api_sync_refresh"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user profile
         * @description Returns the authenticated user's full profile. Sensitive fields (email, phone, lastName) are partially masked.
         */
        get: operations["get_api_user_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update user profile
         * @description Updates one or more profile fields. All fields are optional — only provided fields are changed.
         */
        patch: operations["patch_api_user_profile_update"];
        trace?: never;
    };
    "/api/user/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update user preferences
         * @description Updates language and/or notification preferences. All fields are optional.
         */
        patch: operations["patch_api_user_preferences_update"];
        trace?: never;
    };
    "/api/user/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password
         * @description Changes the authenticated user's password. Requires the current password for verification.
         *     On success, revokes all other sessions (keeps the current session alive via X-Refresh-Token header).
         */
        post: operations["post_api_user_password_change"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request account deletion
         * @description Submits a request to delete the authenticated user's account. The account is NOT deleted
         *     immediately — instead, a notification is sent to the backoffice support team who will
         *     process the request manually. The user receives a confirmation email.
         */
        post: operations["post_api_user_account_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /**
                 * @description Machine-readable error code
                 * @example VALIDATION_ERROR
                 */
                code: string;
                /**
                 * @description Human-readable error message
                 * @example Validation failed.
                 */
                message: string;
                /**
                 * @description Field-level validation errors (only for VALIDATION_ERROR)
                 * @example {
                 *       "email": [
                 *         "This value is not a valid email address."
                 *       ]
                 *     }
                 */
                details?: {
                    [key: string]: string[];
                };
            };
        };
        PolicyResponse: {
            /** @description Policy identifier */
            id: string;
            /**
             * @description Policy series prefix (e.g. POL, PAD, FAC)
             * @example POL
             */
            policySeries?: string | null;
            /** @example 2026-001234 */
            policyNumber: string;
            /**
             * @description Payment transaction reference
             * @example abc123def456
             */
            transactionId?: string | null;
            /**
             * @description Links home combo policies (pad + facultative) belonging to the same package
             * @example 6a0db5bece2994fa7e92202b
             */
            comboId?: string | null;
            /** @enum {string} */
            type: "rca" | "casco" | "casco_econom" | "casco_perfect_cover" | "pad" | "home" | "travel" | "health" | "life" | "accidents" | "accidents_taxi" | "accidents_traveler" | "breakdown" | "cmr" | "rcp" | "other";
            /** @enum {string} */
            status: "active" | "expired" | "cancelled" | "pending";
            /** @example Allianz Tiriac */
            insurer?: string | null;
            /**
             * @description Whether the policy is currently active
             * @example true
             */
            active: boolean;
            /**
             * @description Reference linking back to the originating quote
             * @example RCAQ-501234
             */
            quoteRef?: string | null;
            /**
             * @description Map of file_type to file_id from policy_details.file_ids. Use with GET /user/policies/download/{transactionId}/{fileId}
             * @example {
             *       "policy_pdf": "6a0db693643c04561b15b255"
             *     }
             */
            fileIds?: {
                [key: string]: string;
            };
            /**
             * @description Home/pad system only. pad=PAD obligatoriu, facultative=facultativa
             * @enum {string|null}
             */
            insuranceType?: "pad" | "facultative" | null;
            /** @description Structured data with product details and insured person info */
            data?: {
                /** @description System-specific product data (vehicle plate+vin for auto, address for home, destination+days for travel) */
                product?: Record<string, never>;
                insured?: {
                    /** @example Ion Popescu */
                    name?: string;
                    /**
                     * @description Masked CNP (first 3 + last 2 visible)
                     * @example 190********56
                     */
                    cnp?: string | null;
                };
            };
            /**
             * Format: float
             * @example 920
             */
            premium: number;
            /** @example RON */
            currency: string;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00+00:00
             */
            startDate: string;
            /**
             * Format: date-time
             * @example 2027-01-01T00:00:00+00:00
             */
            endDate: string;
            /**
             * @description Computed days until endDate (negative if expired)
             * @example 333
             */
            daysUntilExpiry: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        QuoteSyncStateResponse: {
            /**
             * @description Legacy quote_input_params._id — use with POST /user/quotes/offer-url
             * @example 6a0db36469ad58211a6f0c29
             */
            quoteInputParamsId?: string;
            /** @description Middleware quote _id */
            quoteId?: string | null;
            quoteRef?: string | null;
            quoteType?: string | null;
            /** @enum {string} */
            status?: "success" | "failed";
            /** Format: date-time */
            lastSyncAt?: string | null;
        };
        PolicySyncStateResponse: {
            /** @description Legacy quote_input._id */
            quoteInputId?: string;
            /** @description Middleware policy _id */
            policyId?: string | null;
            policyNumber?: string | null;
            policyType?: string | null;
            /** @enum {string} */
            status?: "success" | "failed";
            /** Format: date-time */
            lastSyncAt?: string | null;
        };
        QuoteResponse: {
            /** @description Quote identifier */
            id: string;
            /**
             * @description Legacy quote_input_params._id — use with POST /user/quotes/offer-url
             * @example 6a0db36469ad58211a6f0c29
             */
            quoteInputParamsId?: string | null;
            /**
             * @description Unique quote reference
             * @example RCAQ-501234
             */
            quoteRef?: string | null;
            /** @enum {string} */
            type: "rca" | "casco" | "casco_econom" | "casco_perfect_cover" | "pad" | "home" | "travel" | "health" | "life" | "accidents" | "accidents_taxi" | "accidents_traveler" | "breakdown" | "cmr" | "rcp" | "other";
            /**
             * @description Home/pad system only. Derived from insurer_details insurance_type.
             * @enum {string|null}
             */
            insuranceType?: "pad" | "facultative" | null;
            /**
             * Format: date-time
             * @description When the quote was created/requested
             */
            quoteDate?: string | null;
            /**
             * Format: date-time
             * @description Desired coverage start date
             */
            quoteStartDate?: string | null;
            /**
             * @description Whether the quote is still a valid/active offer
             * @example true
             */
            active: boolean;
            /** @description Structured data with product details and insured person info */
            data?: {
                /** @description System-specific product data (vehicle plate+vin for auto, address for home, destination+days for travel) */
                product?: Record<string, never>;
                insured?: {
                    /** @example Ion Popescu */
                    name?: string;
                    /**
                     * @description Masked CNP (first 3 + last 2 visible)
                     * @example 190********56
                     */
                    cnp?: string | null;
                };
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ReminderResponse: {
            /** @description MongoDB ObjectId */
            id: string;
            /** @example Renew RCA policy */
            title: string;
            note?: string | null;
            /** Format: date-time */
            remindAt: string;
            /** @example false */
            isDone: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Full user profile (sensitive fields partially masked) */
        UserProfile: {
            /** @description HMAC-SHA256 hash of user ID (opaque, consistent across requests) */
            id: string;
            /** @example us***@example.com */
            email: string;
            /** @example ionpopescu */
            username: string;
            parentUsername?: string | null;
            /** @example Ion */
            firstName?: string | null;
            /**
             * @description Masked to initial
             * @example P.
             */
            lastName?: string | null;
            /** @example Ion P. */
            fullName?: string | null;
            /**
             * @description Partially masked
             * @example +40*****678
             */
            phone?: string | null;
            /** @example ro */
            country: string;
            /** @description Legacy person sub-document */
            person?: Record<string, never>;
            /** @description Legacy contact sub-document */
            contact?: Record<string, never>;
            /** @description Legacy address sub-document */
            address?: Record<string, never>;
            /** @description Legacy company sub-document */
            company?: Record<string, never>;
            twoFactorEnabled: boolean;
            /** @enum {string|null} */
            twoFactorMethod?: "totp" | "email" | null;
            preferences: {
                /** @enum {string} */
                language?: "ro" | "en" | "fr" | "de";
                notifications?: boolean;
            };
            /** @enum {string} */
            source: "registration" | "legacy_sync";
            /** Format: date-time */
            createdAt: string;
        };
        TwoFactorVerifyRequest: {
            pre_auth_token: string;
            totp_code: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        ForgotPasswordRequest: {
            email: string;
        };
        VerifyResetCodeRequest: {
            email: string;
            code: string;
        };
        ResetPasswordRequest: {
            reset_token: string;
            new_password: string;
        };
        Confirm2FARequest: {
            totp_code: string;
        };
        Disable2FARequest: {
            password: string;
        };
        CreateReminderRequest: {
            title: string;
            remindAt: string;
            /** @default null */
            note: string | null;
        };
        UpdateReminderRequest: {
            /** @default null */
            title: string | null;
            /** @default null */
            remindAt: string | null;
            /** @default null */
            note: string | null;
            isDone?: boolean | null;
        };
        UpdateProfileRequest: {
            /** @default null */
            firstName: string | null;
            /** @default null */
            lastName: string | null;
            /** @default null */
            phone: string | null;
        };
        UpdatePreferencesRequest: {
            /**
             * @default null
             * @enum {string|null}
             */
            language: "ro" | "en" | "fr" | "de" | null;
            /** @default null */
            notifications: boolean | null;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_api_auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example secret123
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful (with or without 2FA) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        requires_2fa: boolean;
                        /** @description RS256 JWT (15 min TTL) */
                        access_token: string;
                        /** @description Opaque refresh token (7 day TTL) */
                        refresh_token: string;
                        user: {
                            /** @description HMAC-SHA256 hashed user ID */
                            id?: string;
                            username?: string;
                        };
                    } | {
                        /** @example true */
                        requires_2fa: boolean;
                        /** @description Short-lived JWT (5 min TTL, scope=pre_auth) */
                        pre_auth_token: string;
                        /** @enum {string} */
                        two_factor_method: "totp" | "email";
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many login attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_auth_public_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public key returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @description PEM-encoded RSA public key */
                            public_key?: string;
                            /** @example RS256 */
                            algorithm?: string;
                        };
                    };
                };
            };
        };
    };
    post_api_auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example newuser@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example securePass1
                     */
                    password: string;
                    /**
                     * Format: password
                     * @description Optional password confirmation
                     */
                    confirmPassword?: string;
                    /** @example Ion */
                    firstName?: string;
                    /** @example Popescu */
                    lastName?: string;
                    /** @example +40712345678 */
                    phone?: string;
                    /** @description Derived from email prefix if omitted */
                    username?: string;
                };
            };
        };
        responses: {
            /** @description Registration successful — user is auto-logged-in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token: string;
                        refresh_token: string;
                        user: {
                            id?: string;
                            username?: string;
                        };
                    };
                };
            };
            /** @description Email or username already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_auth_two_factor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Pre-auth JWT from login response */
                    pre_auth_token: string;
                    /**
                     * @description 6-digit TOTP or email OTP code
                     * @example 123456
                     */
                    totp_code: string;
                };
            };
        };
        responses: {
            /** @description 2FA verification successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token: string;
                        refresh_token: string;
                        user: {
                            id?: string;
                            username?: string;
                        };
                    };
                };
            };
            /** @description Invalid or expired 2FA code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Opaque refresh token from login/previous refresh */
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Token refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token: string;
                        refresh_token: string;
                    };
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Logged out successfully. */
                        message?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_auth_forgot_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example user@example.com
                     */
                    email: string;
                };
            };
        };
        responses: {
            /** @description OTP sent (or silently ignored if email not found) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example If an account exists for this email, a reset code has been sent. */
                        message?: string;
                    };
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_auth_verify_reset_code: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * @description 6-digit OTP from email
                     * @example 123456
                     */
                    code: string;
                };
            };
        };
        responses: {
            /** @description OTP verified — reset token returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description One-time reset token for POST /auth/reset-password */
                        reset_token: string;
                    };
                };
            };
            /** @description Invalid or expired OTP */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_auth_reset_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Token from POST /auth/verify-reset-code */
                    reset_token: string;
                    /** Format: password */
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Password reset successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Password has been reset successfully. */
                        message?: string;
                    };
                };
            };
            /** @description Invalid or expired reset token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_auth_two_factor_enable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Defaults to "totp" if omitted
                     * @example totp
                     * @enum {string}
                     */
                    method?: "totp" | "email";
                };
            };
        };
        responses: {
            /** @description 2FA setup initiated or enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Base32-encoded TOTP secret */
                        secret: string;
                        /** @description otpauth:// URI for QR code generation */
                        provisioningUri: string;
                    } | {
                        /** @example Email two-factor authentication has been enabled. */
                        message?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid 2FA method */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_auth_two_factor_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 123456 */
                    totp_code: string;
                };
            };
        };
        responses: {
            /** @description 2FA confirmed and active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Two-factor authentication has been enabled. */
                        message?: string;
                    };
                };
            };
            /** @description Invalid TOTP code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_auth_two_factor_resend_code: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Pre-auth JWT from login response */
                    pre_auth_token: string;
                };
            };
        };
        responses: {
            /** @description Code resent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example A new verification code has been sent to your email. */
                        message?: string;
                    };
                };
            };
            /** @description Invalid pre-auth token or wrong 2FA method */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_auth_two_factor_disable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: password
                     * @description Current account password
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description 2FA disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Two-factor authentication has been disabled. */
                        message?: string;
                    };
                };
            };
            /** @description Invalid password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_dashboard_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        policies?: {
                            /** @example 5 */
                            total?: number;
                            /** @example 3 */
                            active?: number;
                            /**
                             * @description Count per policy type
                             * @example {"rca": 2, "casco": 1, "home": 2}
                             */
                            byType?: Record<string, never>;
                            /** @description Active policies expiring within 30 days */
                            expiringSoon?: {
                                id?: string;
                                policyNumber?: string;
                                type?: string;
                                /** Format: date */
                                endDate?: string;
                            }[];
                        };
                        quotes?: {
                            /** @example 8 */
                            total?: number;
                            /** @example 2 */
                            pending?: number;
                        };
                        notifications?: {
                            /** @example 3 */
                            unread?: number;
                            /** @example 12 */
                            total?: number;
                        };
                        reminders?: {
                            /** @description Reminders due within 7 days (not done) */
                            upcoming?: {
                                id?: string;
                                title?: string;
                                /** Format: date-time */
                                remindAt?: string;
                            }[];
                            /** @example 4 */
                            total?: number;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_notifications_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        notifications?: {
                            id?: string;
                            /** @enum {string} */
                            type?: "policy_expiry" | "quote_accepted" | "system" | "reminder";
                            title?: string;
                            body?: string;
                            /** @description Additional type-specific metadata */
                            meta?: Record<string, never>;
                            isRead?: boolean;
                            /** Format: date-time */
                            createdAt?: string;
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_api_notifications_mark_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Notification MongoDB ObjectId */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated notification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        type?: string;
                        title?: string;
                        body?: string;
                        meta?: Record<string, never>;
                        /** @example true */
                        isRead?: boolean;
                        /** Format: date-time */
                        createdAt?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Notification not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_api_notifications_mark_all_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All marked as read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example All notifications marked as read. */
                        message?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_api_notifications_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Notification MongoDB ObjectId */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Notification not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_policies_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: "active" | "expired" | "cancelled" | "pending";
                type?: "rca" | "casco" | "casco_econom" | "casco_perfect_cover" | "pad" | "home" | "travel" | "health" | "life" | "accidents" | "accidents_taxi" | "accidents_traveler" | "breakdown" | "cmr" | "rcp" | "other";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated policy list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PolicyResponse"][];
                        /** @example 42 */
                        total?: number;
                        /** @example 1 */
                        page?: number;
                        /** @example 20 */
                        limit?: number;
                        /** @example 3 */
                        pages?: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_policies_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectId */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Policy not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_policies_download_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Policy transaction ID */
                transactionId: string;
                /** @description File ID from policy fileIds map */
                fileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Download URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example https://www.asigurari.ro/app/broker/file/rjzLN2VjR7I... */
                        downloadUrl?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Policy or document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_policies_sync_states: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of policy sync states */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PolicySyncStateResponse"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_quotes_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filter by active state (true/false) */
                active?: boolean;
                type?: "rca" | "casco" | "casco_econom" | "casco_perfect_cover" | "pad" | "home" | "travel" | "health" | "life" | "accidents" | "accidents_taxi" | "accidents_traveler" | "breakdown" | "cmr" | "rcp" | "other";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated quote list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["QuoteResponse"][];
                        /** @example 15 */
                        total?: number;
                        /** @example 1 */
                        page?: number;
                        /** @example 20 */
                        limit?: number;
                        /** @example 1 */
                        pages?: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_quotes_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectId */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quote details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Quote not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_quotes_offer_url: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Legacy quoteInputParamsId
                     * @example 6a0db36469ad58211a6f0c29
                     */
                    quote_input_params_id: string;
                };
            };
        };
        responses: {
            /** @description Offer URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example https://www.asigurari.ro/home/oferte/... */
                        offerUrl?: string | null;
                    };
                };
            };
            /** @description Missing parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Quote does not belong to user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_quotes_sync_states: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of quote sync states */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["QuoteSyncStateResponse"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_reminders_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminder list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        reminders?: components["schemas"]["ReminderResponse"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_reminders_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Renew RCA policy */
                    title: string;
                    /**
                     * Format: date-time
                     * @example 2026-05-15T09:00:00+03:00
                     */
                    remindAt: string;
                    /** @example Policy #12345 expires */
                    note?: string | null;
                };
            };
        };
        responses: {
            /** @description Reminder created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    put_api_reminders_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Reminder MongoDB ObjectId */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    /** Format: date-time */
                    remindAt?: string;
                    note?: string | null;
                    isDone?: boolean;
                };
            };
        };
        responses: {
            /** @description Updated reminder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Reminder not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_api_reminders_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Reminder MongoDB ObjectId */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminder deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Reminder not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_sessions_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessions?: {
                            /** @description Session ID (MongoDB ObjectId) */
                            id?: string;
                            /** @example 192.168.1.42 */
                            ip?: string;
                            userAgent?: string;
                            /** Format: date-time */
                            lastActivityAt?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** @description True if this is the requesting session */
                            current?: boolean;
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_api_sessions_delete_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All other sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_api_sessions_delete_one: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session MongoDB ObjectId */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_sync_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync refresh result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        hasChanges?: boolean;
                        /** @example 1 */
                        newPolicies?: number;
                        /** @example 0 */
                        updatedPolicies?: number;
                        /** @example 0 */
                        removedPolicies?: number;
                        /** @example 2 */
                        newQuotes?: number;
                        /** @example 0 */
                        updatedQuotes?: number;
                        /** @example 0 */
                        removedQuotes?: number;
                        /** Format: date-time */
                        syncedAt?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_user_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description HMAC-SHA256 hashed user ID */
                        id?: string;
                        /**
                         * @description Partially masked
                         * @example us***@example.com
                         */
                        email?: string;
                        /** @example ionpopescu */
                        username?: string;
                        parentUsername?: string | null;
                        /** @example Ion */
                        firstName?: string | null;
                        /**
                         * @description Masked to initial
                         * @example P.
                         */
                        lastName?: string | null;
                        /** @example Ion P. */
                        fullName?: string | null;
                        /**
                         * @description Partially masked
                         * @example +40*****678
                         */
                        phone?: string | null;
                        /** @example ro */
                        country?: string;
                        /** @description Legacy person sub-document */
                        person?: Record<string, never>;
                        /** @description Legacy contact sub-document */
                        contact?: Record<string, never>;
                        /** @description Legacy address sub-document */
                        address?: Record<string, never>;
                        /** @description Legacy company sub-document */
                        company?: Record<string, never>;
                        twoFactorEnabled?: boolean;
                        /** @enum {string|null} */
                        twoFactorMethod?: "totp" | "email" | null;
                        preferences?: {
                            /** @enum {string} */
                            language?: "ro" | "en" | "fr" | "de";
                            notifications?: boolean;
                        };
                        /** @enum {string} */
                        source?: "registration" | "legacy_sync";
                        /** Format: date-time */
                        createdAt?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_api_user_profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Ion */
                    firstName?: string;
                    /** @example Popescu */
                    lastName?: string;
                    /** @example +40712345678 */
                    phone?: string;
                };
            };
        };
        responses: {
            /** @description Updated profile (same shape as GET /user/profile) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_api_user_preferences_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    language?: "ro" | "en" | "fr" | "de";
                    notifications?: boolean;
                };
            };
        };
        responses: {
            /** @description Updated preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        preferences?: {
                            /** @example ro */
                            language?: string;
                            /** @example true */
                            notifications?: boolean;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_user_password_change: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    current_password: string;
                    /** Format: password */
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Password changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Password updated successfully. */
                        message?: string;
                    };
                };
            };
            /** @description Invalid current password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error or same password */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_user_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion request submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Your account deletion request has been submitted. Our support team will contact you shortly. */
                        message?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
